// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using servidor;

#nullable disable

namespace servidor.Migrations
{
    [DbContext(typeof(TiendaDbContext))]
    [Migration("20250614043730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("servidor.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("servidor.ItemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsCompra");
                });

            modelBuilder.Entity("servidor.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "El último smartphone de Apple con chip A16 Bionic.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "iPhone 14 Pro",
                            Precio = 999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "El buque insignia de Samsung con un S Pen integrado.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Samsung Galaxy S23 Ultra",
                            Precio = 1199.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "La magia de Google en un teléfono, con el chip Tensor G2.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Google Pixel 7 Pro",
                            Precio = 899.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Protección suave y elegante para tu iPhone.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Funda de Silicona para iPhone",
                            Precio = 49.00m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Carga tu dispositivo a toda velocidad.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Cargador Rápido USB-C 30W",
                            Precio = 35.50m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Cancelación de ruido activa y audio espacial.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "AirPods Pro (2da Gen)",
                            Precio = 249.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Máxima protección contra rayones y golpes.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Protector de Pantalla de Vidrio",
                            Precio = 25.00m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Monitor de salud avanzado y diseño moderno.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Samsung Galaxy Watch 5",
                            Precio = 279.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Nunca te quedes sin batería fuera de casa.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Batería Externa 10000mAh",
                            Precio = 45.00m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Mantén tu teléfono seguro y a la vista mientras conduces.",
                            ImagenUrl = "https://placehold.co/300x200/png",
                            Nombre = "Soporte de Coche Magnético",
                            Precio = 22.99m,
                            Stock = 180
                        });
                });

            modelBuilder.Entity("servidor.ItemCompra", b =>
                {
                    b.HasOne("servidor.Compra", "Compra")
                        .WithMany("Items")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("servidor.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("servidor.Compra", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
